version: "3"

services:
  cont1:
      container_name: cont1
      image: cont1
      ports:
        - 8000:8080
      volumes:
        - ./settings.json:/app/settings.json
  cont2:
    container_name: cont2
    image: cont2
    ports:
      - 8001:8080
    volumes:
      - ./settings.json:/app/settings.json

networks:
  default:
    