swagger: '2.0'
info:
  description: Набор сервисов для учета на предприятии /ООО Ромашка/
  version: "1.0.0"
  title: RestApi

produces:
  - application/json
  - application/xml
  - application/text

basePath: "/api"

paths:
  /reports/formats:
    get:
      tags:
        - filter models
      summary: Получить список форматов для отчетов
      operationId: main.formats
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка     


  /reports/range/{format}:
    get:
      tags:
        - filter models
      summary: Получить список единиц измерения
      operationId: main.reports_range
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
    - name: format
      in: path
      description: Уникальный код формата
      required: true
      type: string 

  /reports/group/{format}:
    get:
      tags:
        - filter models
      summary: Получить список групп номенклатур
      operationId: main.reports_group
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
    - name: format
      in: path
      description: Уникальный код формата
      required: true
      type: string

  /reports/nomenclature/{format}:
    get:
      tags:
        - filter models
      summary: Получить список номенклатур
      operationId: main.reports_nomenclature
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
    - name: format
      in: path
      description: Уникальный код формата
      required: true
      type: string

  /reports/recipe/{format}:
    get:
      tags:
        - filter models
      summary: Получить список рецептов
      operationId: main.reports_recipe
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
    - name: format
      in: path
      description: Уникальный код формата
      required: true
      type: string

  /filter/{domain}:
      post:
        tags:
        - filter models
        summary: Фильтрация данных по модели
        operationId: main.filter_data
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - name: domain
            in: path
            required: true
            type: string
            description: Доступные модели для фильтрации nomenclature, group, range, receipt
          - in: body
            name: filter
            description: Доступные фильтры EQUALS, LIKE
            required: true
            schema:
              type: object
              properties:
                name:
                  type: string
                  default: ""
                filter_name:
                  type: string
                  default: "EQUALS"
                unique_code:
                  type: string
                  default: ""
                filter_unique_code:
                  type: string
                  default: "EQUALS"
        responses:
          200:
            description: OK
            schema:
              type: object
          400:
            description: Ошибка ввода данных
            schema:
              type: object
          500:
            description: Ошибка на сервере
          default:
            description: Неизвестная ошибка


  /reports/transactions/{format}:
    get:
      tags:
        - filter warehouse
      summary: Получить список рецептов
      operationId: main.reports_transaction
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
    - name: format
      in: path
      description: Уникальный код формата
      required: true
      type: string
        

# пока не работает
  # /transaction/filter/{domain}:
  #     post:
  #       summary: Фильтрация данных по модели
  #       operationId: main.filter_transaction
  #       consumes:
  #         - application/json
  #       produces:
  #         - application/json
  #       parameters:
  #         - name: domain
  #           in: path
  #           required: true
  #           type: string
  #           description: Доступные модели для фильтрации nomenclature, warehouse
  #         - in: body
  #           name: filter
  #           description: Доступные фильтры EQUALS, LIKE
  #           required: true
  #           schema:
  #             type: object
  #             properties:
  #               name:
  #                 type: string
  #                 default: ""
  #               filter_name:
  #                 type: string
  #                 default: "EQUALS"
  #               unique_code:
  #                 type: string
  #                 default: ""
  #               filter_unique_code:
  #                 type: string
  #                 default: "EQUALS"
  #       responses:
  #         200:
  #           description: OK
  #           schema:
  #             type: object
  #         400:
  #           description: Ошибка ввода данных
  #           schema:
  #             type: object
  #         500:
  #           description: Ошибка на сервере
  #         default:
  #           description: Неизвестная ошибка